// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrbrtdboueedwwbgnzbp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1yYnJ0ZGJvdWVlZHd3YmduemJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4ODc5MDAsImV4cCI6MjA2NjQ2MzkwMH0.KnWAhquukJIo7vgXtpWevG5yk44fsUduDBhXF3k7hOA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);